FROM gradle:8.13.0-jdk21 as builder
WORKDIR /home/gradle/project
# Copy only the files necessary for the build (including the Gradle wrapper, build files, and source)
COPY gradlew gradlew
COPY gradle gradle
COPY build.gradle settings.gradle ./
COPY src src
# facem gradle wrapper executabil si facem build
RUN chmod +x gradlew && ./gradlew clean build --no-daemon

FROM openjdk:21-jdk
WORKDIR /backend
COPY --from=builder /home/gradle/project/build/libs/*.jar /backend/
#trebuie pus acelasi ca portul aplicatiei
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
